{{- range .Values.externalSecrets.credentialTemplates.credentials }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "backstage.fullname" . }}-backend
  namespace: {{ include "backstage.fullname" . }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef }}
    kind: {{ .Values.externalSecrets.secretStoreKind }}
  data:
  - secretKey: ARGOCD_AUTH_TOKEN
    remoteRef:
      key: {{ .Values.externalSecrets.credentialTemplates.remoteRefKey }}/{{ . }}
      property: ARGOCD_AUTH_TOKEN
  - secretKey: GITLAB_TOKEN
    remoteRef:
      key: {{ .Values.externalSecrets.credentialTemplates.remoteRefKey }}/{{ . }}
      property: GITLAB_TOKEN
  - secretKey: root-ca.crt
    remoteRef:
      key: {{ .Values.externalSecrets.credentialTemplates.remoteRefKey }}/{{ . }}
      property: root-ca.crt
  - secretKey: NODE_EXTRA_CA_CERTS
    remoteRef:
      key: {{ .Values.externalSecrets.credentialTemplates.remoteRefKey }}/{{ . }}
      property: NODE_EXTRA_CA_CERTS
{{- end }}
