apiVersion: v1
kind: Service
metadata:
  name: {{ include "backstage.fullname" . }}-backend
  namespace: {{ include "backstage.fullname" . }}
  labels:
    app: {{ include "backstage.fullname" . }}
    component: backend
spec:
  type: {{ .Values.backend.serviceType }}
  ports:
    - port: {{ .Values.backend.servicePort }}
      targetPort: {{ .Values.backend.serviceTargetPort }}
  selector:
    app: {{ include "backstage.fullname" . }}
    component: backend
